add_newline = false
 
[shell]
disabled = false
 
[username]
show_always = true
 
[directory]
truncation_length = 0

[character]
success_symbol = "[🡆](bold green)"
error_symbol = "[✘](bold red)"
vicmd_symbol = "[🡄](bold blue)"
# vimcmd_replace_one_symbol = "[🡄](bold purple)"
# vimcmd_replace_symbol = "[🡄](bold purple)"
# vimcmd_visual_symbol = "[🡄](bold yellow)"
